# Generated by Django 5.1.4 on 2025-01-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salvando_patas', '0002_issue_image_alter_resource_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpoption',
            name='description',
            field=models.TextField(default='descripcion por defecto'),
            preserve_default=False,
        ),
    ]
